all: clean compile run

compile:
	@javac -Xlint:unchecked JavaTest.java cse241/homeworks_3/JavaContainer.java cse241/homeworks_3/JavaSet.java cse241/homeworks_3/JavaVector.java

run: 
	@java JavaTest

clean:
	@rm -f *.class